// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/application.dart';
import 'api/system.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountInfo dco_decode_account_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AccountInfo dco_decode_box_autoadd_account_info(dynamic raw);

  @protected
  DeviceCodeLoginComplete dco_decode_box_autoadd_device_code_login_complete(
    dynamic raw,
  );

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  SecureCredential dco_decode_box_autoadd_secure_credential(dynamic raw);

  @protected
  UsageSnapshot dco_decode_box_autoadd_usage_snapshot(dynamic raw);

  @protected
  CredentialStatus dco_decode_credential_status(dynamic raw);

  @protected
  DeviceCodeLoginComplete dco_decode_device_code_login_complete(dynamic raw);

  @protected
  DeviceCodeLoginPoll dco_decode_device_code_login_poll(dynamic raw);

  @protected
  DeviceCodeLoginStart dco_decode_device_code_login_start(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  HistoryPoint dco_decode_history_point(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<HistoryPoint> dco_decode_list_history_point(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<QuotaWindow> dco_decode_list_quota_window(dynamic raw);

  @protected
  List<ResetCredit> dco_decode_list_reset_credit(dynamic raw);

  @protected
  LoginState dco_decode_login_state(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DeviceCodeLoginComplete?
  dco_decode_opt_box_autoadd_device_code_login_complete(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  SecureCredential? dco_decode_opt_box_autoadd_secure_credential(dynamic raw);

  @protected
  UsageSnapshot? dco_decode_opt_box_autoadd_usage_snapshot(dynamic raw);

  @protected
  List<ResetCredit>? dco_decode_opt_list_reset_credit(dynamic raw);

  @protected
  QuotaWindow dco_decode_quota_window(dynamic raw);

  @protected
  ResetCredit dco_decode_reset_credit(dynamic raw);

  @protected
  SecureCredential dco_decode_secure_credential(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UsageResult dco_decode_usage_result(dynamic raw);

  @protected
  UsageSnapshot dco_decode_usage_snapshot(dynamic raw);

  @protected
  UsageState dco_decode_usage_state(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountInfo sse_decode_account_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AccountInfo sse_decode_box_autoadd_account_info(SseDeserializer deserializer);

  @protected
  DeviceCodeLoginComplete sse_decode_box_autoadd_device_code_login_complete(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SecureCredential sse_decode_box_autoadd_secure_credential(
    SseDeserializer deserializer,
  );

  @protected
  UsageSnapshot sse_decode_box_autoadd_usage_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  CredentialStatus sse_decode_credential_status(SseDeserializer deserializer);

  @protected
  DeviceCodeLoginComplete sse_decode_device_code_login_complete(
    SseDeserializer deserializer,
  );

  @protected
  DeviceCodeLoginPoll sse_decode_device_code_login_poll(
    SseDeserializer deserializer,
  );

  @protected
  DeviceCodeLoginStart sse_decode_device_code_login_start(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  HistoryPoint sse_decode_history_point(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<HistoryPoint> sse_decode_list_history_point(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<QuotaWindow> sse_decode_list_quota_window(SseDeserializer deserializer);

  @protected
  List<ResetCredit> sse_decode_list_reset_credit(SseDeserializer deserializer);

  @protected
  LoginState sse_decode_login_state(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DeviceCodeLoginComplete?
  sse_decode_opt_box_autoadd_device_code_login_complete(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SecureCredential? sse_decode_opt_box_autoadd_secure_credential(
    SseDeserializer deserializer,
  );

  @protected
  UsageSnapshot? sse_decode_opt_box_autoadd_usage_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  List<ResetCredit>? sse_decode_opt_list_reset_credit(
    SseDeserializer deserializer,
  );

  @protected
  QuotaWindow sse_decode_quota_window(SseDeserializer deserializer);

  @protected
  ResetCredit sse_decode_reset_credit(SseDeserializer deserializer);

  @protected
  SecureCredential sse_decode_secure_credential(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UsageResult sse_decode_usage_result(SseDeserializer deserializer);

  @protected
  UsageSnapshot sse_decode_usage_snapshot(SseDeserializer deserializer);

  @protected
  UsageState sse_decode_usage_state(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_info(AccountInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_account_info(
    AccountInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_device_code_login_complete(
    DeviceCodeLoginComplete self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_secure_credential(
    SecureCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_usage_snapshot(
    UsageSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_credential_status(
    CredentialStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_code_login_complete(
    DeviceCodeLoginComplete self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_code_login_poll(
    DeviceCodeLoginPoll self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_code_login_start(
    DeviceCodeLoginStart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_history_point(HistoryPoint self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_history_point(
    List<HistoryPoint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_quota_window(
    List<QuotaWindow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reset_credit(
    List<ResetCredit> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_login_state(LoginState self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_device_code_login_complete(
    DeviceCodeLoginComplete? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_secure_credential(
    SecureCredential? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_usage_snapshot(
    UsageSnapshot? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_reset_credit(
    List<ResetCredit>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_quota_window(QuotaWindow self, SseSerializer serializer);

  @protected
  void sse_encode_reset_credit(ResetCredit self, SseSerializer serializer);

  @protected
  void sse_encode_secure_credential(
    SecureCredential self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usage_result(UsageResult self, SseSerializer serializer);

  @protected
  void sse_encode_usage_snapshot(UsageSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_usage_state(UsageState self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
