// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/application.dart';
import 'api/system.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1885322832;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'ai_usage_core',
        ioDirectory: '../rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<DeviceCodeLoginStart> crateApiApplicationBeginDeviceLogin();

  Future<MimoLoginResult> crateApiApplicationBeginMimoLogin({
    required String username,
    required String password,
  });

  Future<AccountDetails?> crateApiApplicationCachedAccountDetails({
    required String accountIdentityHash,
  });

  Future<ProfileUsage?> crateApiApplicationCachedProfileUsage({
    required String accountIdentityHash,
  });

  Future<UsageResult> crateApiApplicationCachedUsage({
    required AccountInfo account,
  });

  Future<void> crateApiApplicationCancelDeviceLogin({required String loginId});

  Future<MimoLoginResult> crateApiApplicationCompleteMimoWebLogin({
    required String accountCookie,
    required String platformCookie,
  });

  Future<AccountDetails> crateApiApplicationFetchAccountDetails({
    required SecureCredential credential,
    required SyncTrigger trigger,
  });

  Future<ProfileUsage> crateApiApplicationFetchProfileUsage({
    required SecureCredential credential,
    required SyncTrigger trigger,
  });

  Future<DeviceCodeLoginComplete> crateApiApplicationImportCodexAuthJson({
    required List<int> content,
  });

  Future<void> crateApiApplicationInitializeCore({
    required String databasePath,
  });

  Future<String> crateApiSystemPing();

  Future<DeviceCodeLoginPoll> crateApiApplicationPollDeviceLogin({
    required String loginId,
  });

  Future<UsageResult> crateApiApplicationRefreshDeepseekUsage({
    required String apiKey,
    required SyncTrigger trigger,
  });

  Future<UsageResult> crateApiApplicationRefreshMimoUsage({
    required MimoCredential credential,
    required SyncTrigger trigger,
  });

  Future<UsageResult> crateApiApplicationRefreshUsage({
    required SecureCredential credential,
    required SyncTrigger trigger,
  });

  Future<void> crateApiApplicationRemoveAccountData({
    required String accountIdentityHash,
  });

  Future<List<SyncLogEntry>> crateApiApplicationSyncLogs();

  Future<List<HistoryPoint>> crateApiApplicationUsageHistory({
    required String accountIdentityHash,
    required PlatformInt64 since,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<DeviceCodeLoginStart> crateApiApplicationBeginDeviceLogin() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_code_login_start,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationBeginDeviceLoginConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationBeginDeviceLoginConstMeta =>
      const TaskConstMeta(debugName: "begin_device_login", argNames: []);

  @override
  Future<MimoLoginResult> crateApiApplicationBeginMimoLogin({
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mimo_login_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationBeginMimoLoginConstMeta,
        argValues: [username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationBeginMimoLoginConstMeta =>
      const TaskConstMeta(
        debugName: "begin_mimo_login",
        argNames: ["username", "password"],
      );

  @override
  Future<AccountDetails?> crateApiApplicationCachedAccountDetails({
    required String accountIdentityHash,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(accountIdentityHash, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_account_details,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationCachedAccountDetailsConstMeta,
        argValues: [accountIdentityHash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationCachedAccountDetailsConstMeta =>
      const TaskConstMeta(
        debugName: "cached_account_details",
        argNames: ["accountIdentityHash"],
      );

  @override
  Future<ProfileUsage?> crateApiApplicationCachedProfileUsage({
    required String accountIdentityHash,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(accountIdentityHash, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_profile_usage,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationCachedProfileUsageConstMeta,
        argValues: [accountIdentityHash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationCachedProfileUsageConstMeta =>
      const TaskConstMeta(
        debugName: "cached_profile_usage",
        argNames: ["accountIdentityHash"],
      );

  @override
  Future<UsageResult> crateApiApplicationCachedUsage({
    required AccountInfo account,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_account_info(account, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usage_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationCachedUsageConstMeta,
        argValues: [account],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationCachedUsageConstMeta =>
      const TaskConstMeta(debugName: "cached_usage", argNames: ["account"]);

  @override
  Future<void> crateApiApplicationCancelDeviceLogin({required String loginId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(loginId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationCancelDeviceLoginConstMeta,
        argValues: [loginId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationCancelDeviceLoginConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_device_login",
        argNames: ["loginId"],
      );

  @override
  Future<MimoLoginResult> crateApiApplicationCompleteMimoWebLogin({
    required String accountCookie,
    required String platformCookie,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(accountCookie, serializer);
          sse_encode_String(platformCookie, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mimo_login_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationCompleteMimoWebLoginConstMeta,
        argValues: [accountCookie, platformCookie],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationCompleteMimoWebLoginConstMeta =>
      const TaskConstMeta(
        debugName: "complete_mimo_web_login",
        argNames: ["accountCookie", "platformCookie"],
      );

  @override
  Future<AccountDetails> crateApiApplicationFetchAccountDetails({
    required SecureCredential credential,
    required SyncTrigger trigger,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_secure_credential(credential, serializer);
          sse_encode_sync_trigger(trigger, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_account_details,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationFetchAccountDetailsConstMeta,
        argValues: [credential, trigger],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationFetchAccountDetailsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_account_details",
        argNames: ["credential", "trigger"],
      );

  @override
  Future<ProfileUsage> crateApiApplicationFetchProfileUsage({
    required SecureCredential credential,
    required SyncTrigger trigger,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_secure_credential(credential, serializer);
          sse_encode_sync_trigger(trigger, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_profile_usage,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationFetchProfileUsageConstMeta,
        argValues: [credential, trigger],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationFetchProfileUsageConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_profile_usage",
        argNames: ["credential", "trigger"],
      );

  @override
  Future<DeviceCodeLoginComplete> crateApiApplicationImportCodexAuthJson({
    required List<int> content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_code_login_complete,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationImportCodexAuthJsonConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationImportCodexAuthJsonConstMeta =>
      const TaskConstMeta(
        debugName: "import_codex_auth_json",
        argNames: ["content"],
      );

  @override
  Future<void> crateApiApplicationInitializeCore({
    required String databasePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationInitializeCoreConstMeta,
        argValues: [databasePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationInitializeCoreConstMeta =>
      const TaskConstMeta(
        debugName: "initialize_core",
        argNames: ["databasePath"],
      );

  @override
  Future<String> crateApiSystemPing() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSystemPingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSystemPingConstMeta =>
      const TaskConstMeta(debugName: "ping", argNames: []);

  @override
  Future<DeviceCodeLoginPoll> crateApiApplicationPollDeviceLogin({
    required String loginId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(loginId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_code_login_poll,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationPollDeviceLoginConstMeta,
        argValues: [loginId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationPollDeviceLoginConstMeta =>
      const TaskConstMeta(
        debugName: "poll_device_login",
        argNames: ["loginId"],
      );

  @override
  Future<UsageResult> crateApiApplicationRefreshDeepseekUsage({
    required String apiKey,
    required SyncTrigger trigger,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(apiKey, serializer);
          sse_encode_sync_trigger(trigger, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usage_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApplicationRefreshDeepseekUsageConstMeta,
        argValues: [apiKey, trigger],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationRefreshDeepseekUsageConstMeta =>
      const TaskConstMeta(
        debugName: "refresh_deepseek_usage",
        argNames: ["apiKey", "trigger"],
      );

  @override
  Future<UsageResult> crateApiApplicationRefreshMimoUsage({
    required MimoCredential credential,
    required SyncTrigger trigger,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_mimo_credential(credential, serializer);
          sse_encode_sync_trigger(trigger, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usage_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApplicationRefreshMimoUsageConstMeta,
        argValues: [credential, trigger],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationRefreshMimoUsageConstMeta =>
      const TaskConstMeta(
        debugName: "refresh_mimo_usage",
        argNames: ["credential", "trigger"],
      );

  @override
  Future<UsageResult> crateApiApplicationRefreshUsage({
    required SecureCredential credential,
    required SyncTrigger trigger,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_secure_credential(credential, serializer);
          sse_encode_sync_trigger(trigger, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usage_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApplicationRefreshUsageConstMeta,
        argValues: [credential, trigger],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationRefreshUsageConstMeta =>
      const TaskConstMeta(
        debugName: "refresh_usage",
        argNames: ["credential", "trigger"],
      );

  @override
  Future<void> crateApiApplicationRemoveAccountData({
    required String accountIdentityHash,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(accountIdentityHash, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationRemoveAccountDataConstMeta,
        argValues: [accountIdentityHash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationRemoveAccountDataConstMeta =>
      const TaskConstMeta(
        debugName: "remove_account_data",
        argNames: ["accountIdentityHash"],
      );

  @override
  Future<List<SyncLogEntry>> crateApiApplicationSyncLogs() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_sync_log_entry,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationSyncLogsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationSyncLogsConstMeta =>
      const TaskConstMeta(debugName: "sync_logs", argNames: []);

  @override
  Future<List<HistoryPoint>> crateApiApplicationUsageHistory({
    required String accountIdentityHash,
    required PlatformInt64 since,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(accountIdentityHash, serializer);
          sse_encode_i_64(since, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_history_point,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationUsageHistoryConstMeta,
        argValues: [accountIdentityHash, since],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationUsageHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "usage_history",
        argNames: ["accountIdentityHash", "since"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AccountDetails dco_decode_account_details(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AccountDetails(
      createdAt: dco_decode_i_64(arr[0]),
      email: dco_decode_opt_String(arr[1]),
      fetchedAt: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  AccountInfo dco_decode_account_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return AccountInfo(
      provider: dco_decode_provider_kind(arr[0]),
      identityHash: dco_decode_String(arr[1]),
      email: dco_decode_opt_String(arr[2]),
      plan: dco_decode_opt_String(arr[3]),
      workspaceId: dco_decode_opt_String(arr[4]),
      isFedramp: dco_decode_bool(arr[5]),
      loginState: dco_decode_login_state(arr[6]),
      lastSuccessfulRefresh: dco_decode_opt_box_autoadd_i_64(arr[7]),
      credentialStatus: dco_decode_credential_status(arr[8]),
    );
  }

  @protected
  BalanceMetric dco_decode_balance_metric(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BalanceMetric(
      id: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      amount: dco_decode_String(arr[2]),
      currency: dco_decode_opt_String(arr[3]),
      primary: dco_decode_bool(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AccountDetails dco_decode_box_autoadd_account_details(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_account_details(raw);
  }

  @protected
  AccountInfo dco_decode_box_autoadd_account_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_account_info(raw);
  }

  @protected
  CreditsSnapshot dco_decode_box_autoadd_credits_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_credits_snapshot(raw);
  }

  @protected
  DeviceCodeLoginComplete dco_decode_box_autoadd_device_code_login_complete(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_device_code_login_complete(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  MimoCredential dco_decode_box_autoadd_mimo_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mimo_credential(raw);
  }

  @protected
  ProfileUsage dco_decode_box_autoadd_profile_usage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_profile_usage(raw);
  }

  @protected
  SecureCredential dco_decode_box_autoadd_secure_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_secure_credential(raw);
  }

  @protected
  UsageSnapshot dco_decode_box_autoadd_usage_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_usage_snapshot(raw);
  }

  @protected
  CredentialStatus dco_decode_credential_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CredentialStatus.values[raw as int];
  }

  @protected
  CreditsSnapshot dco_decode_credits_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CreditsSnapshot(
      hasCredits: dco_decode_bool(arr[0]),
      unlimited: dco_decode_bool(arr[1]),
      balance: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  DailyTokenBucket dco_decode_daily_token_bucket(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DailyTokenBucket(
      startDate: dco_decode_String(arr[0]),
      tokens: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  DeviceCodeLoginComplete dco_decode_device_code_login_complete(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DeviceCodeLoginComplete(
      credential: dco_decode_secure_credential(arr[0]),
      account: dco_decode_account_info(arr[1]),
    );
  }

  @protected
  DeviceCodeLoginPoll dco_decode_device_code_login_poll(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DeviceCodeLoginPoll(
      pending: dco_decode_bool(arr[0]),
      completed: dco_decode_opt_box_autoadd_device_code_login_complete(arr[1]),
    );
  }

  @protected
  DeviceCodeLoginStart dco_decode_device_code_login_start(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DeviceCodeLoginStart(
      loginId: dco_decode_String(arr[0]),
      verificationUrl: dco_decode_String(arr[1]),
      userCode: dco_decode_String(arr[2]),
      pollIntervalSeconds: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  HistoryPoint dco_decode_history_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return HistoryPoint(
      timestamp: dco_decode_i_64(arr[0]),
      windowId: dco_decode_String(arr[1]),
      usedPercent: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<BalanceMetric> dco_decode_list_balance_metric(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_balance_metric).toList();
  }

  @protected
  List<DailyTokenBucket> dco_decode_list_daily_token_bucket(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_daily_token_bucket).toList();
  }

  @protected
  List<HistoryPoint> dco_decode_list_history_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_history_point).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProviderQuotaMetric> dco_decode_list_provider_quota_metric(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_provider_quota_metric)
        .toList();
  }

  @protected
  List<QuotaWindow> dco_decode_list_quota_window(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_quota_window).toList();
  }

  @protected
  List<ResetCredit> dco_decode_list_reset_credit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_reset_credit).toList();
  }

  @protected
  List<SyncLogEntry> dco_decode_list_sync_log_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sync_log_entry).toList();
  }

  @protected
  LoginState dco_decode_login_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LoginState.values[raw as int];
  }

  @protected
  MimoCredential dco_decode_mimo_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MimoCredential(
      userId: dco_decode_String(arr[0]),
      passToken: dco_decode_String(arr[1]),
      serviceToken: dco_decode_String(arr[2]),
      serviceSlh: dco_decode_String(arr[3]),
      servicePh: dco_decode_String(arr[4]),
    );
  }

  @protected
  MimoLoginResult dco_decode_mimo_login_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MimoLoginResult(
      account: dco_decode_opt_box_autoadd_account_info(arr[0]),
      credential: dco_decode_opt_box_autoadd_mimo_credential(arr[1]),
      challengeUrl: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  AccountDetails? dco_decode_opt_box_autoadd_account_details(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_account_details(raw);
  }

  @protected
  AccountInfo? dco_decode_opt_box_autoadd_account_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_account_info(raw);
  }

  @protected
  CreditsSnapshot? dco_decode_opt_box_autoadd_credits_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_credits_snapshot(raw);
  }

  @protected
  DeviceCodeLoginComplete?
  dco_decode_opt_box_autoadd_device_code_login_complete(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_device_code_login_complete(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  MimoCredential? dco_decode_opt_box_autoadd_mimo_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_mimo_credential(raw);
  }

  @protected
  ProfileUsage? dco_decode_opt_box_autoadd_profile_usage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_profile_usage(raw);
  }

  @protected
  SecureCredential? dco_decode_opt_box_autoadd_secure_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_secure_credential(raw);
  }

  @protected
  UsageSnapshot? dco_decode_opt_box_autoadd_usage_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_usage_snapshot(raw);
  }

  @protected
  List<ResetCredit>? dco_decode_opt_list_reset_credit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_reset_credit(raw);
  }

  @protected
  ProfileUsage dco_decode_profile_usage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ProfileUsage(
      summary: dco_decode_token_usage_summary(arr[0]),
      dailyUsageBuckets: dco_decode_list_daily_token_bucket(arr[1]),
      fetchedAt: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  ProviderKind dco_decode_provider_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ProviderKind.values[raw as int];
  }

  @protected
  ProviderQuotaMetric dco_decode_provider_quota_metric(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ProviderQuotaMetric(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      used: dco_decode_String(arr[2]),
      limit: dco_decode_String(arr[3]),
      remaining: dco_decode_String(arr[4]),
      usedPercent: dco_decode_f_64(arr[5]),
      expiresAt: dco_decode_opt_box_autoadd_i_64(arr[6]),
      unit: dco_decode_String(arr[7]),
    );
  }

  @protected
  QuotaWindow dco_decode_quota_window(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return QuotaWindow(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      usedPercent: dco_decode_f_64(arr[2]),
      resetAt: dco_decode_i_64(arr[3]),
      windowSeconds: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  ResetCredit dco_decode_reset_credit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ResetCredit(
      id: dco_decode_String(arr[0]),
      status: dco_decode_String(arr[1]),
      grantedAt: dco_decode_i_64(arr[2]),
      expiresAt: dco_decode_opt_box_autoadd_i_64(arr[3]),
      title: dco_decode_opt_String(arr[4]),
      description: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  SecureCredential dco_decode_secure_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SecureCredential(
      idToken: dco_decode_String(arr[0]),
      accessToken: dco_decode_String(arr[1]),
      refreshToken: dco_decode_String(arr[2]),
    );
  }

  @protected
  SyncLogEntry dco_decode_sync_log_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return SyncLogEntry(
      id: dco_decode_i_64(arr[0]),
      accountIdentityHash: dco_decode_String(arr[1]),
      trigger: dco_decode_sync_trigger(arr[2]),
      endpoint: dco_decode_String(arr[3]),
      startedAt: dco_decode_i_64(arr[4]),
      durationMs: dco_decode_i_64(arr[5]),
      statusCode: dco_decode_opt_box_autoadd_i_64(arr[6]),
      resultState: dco_decode_String(arr[7]),
      errorKind: dco_decode_opt_String(arr[8]),
      responseBody: dco_decode_String(arr[9]),
      truncated: dco_decode_bool(arr[10]),
    );
  }

  @protected
  SyncTrigger dco_decode_sync_trigger(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SyncTrigger.values[raw as int];
  }

  @protected
  TokenUsageSummary dco_decode_token_usage_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TokenUsageSummary(
      lifetimeTokens: dco_decode_opt_box_autoadd_i_64(arr[0]),
      peakDailyTokens: dco_decode_opt_box_autoadd_i_64(arr[1]),
      longestRunningTurnSec: dco_decode_opt_box_autoadd_i_64(arr[2]),
      currentStreakDays: dco_decode_opt_box_autoadd_i_64(arr[3]),
      longestStreakDays: dco_decode_opt_box_autoadd_i_64(arr[4]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UsageResult dco_decode_usage_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return UsageResult(
      snapshot: dco_decode_opt_box_autoadd_usage_snapshot(arr[0]),
      state: dco_decode_usage_state(arr[1]),
      showingCachedData: dco_decode_bool(arr[2]),
      message: dco_decode_opt_String(arr[3]),
      retryAfterSeconds: dco_decode_opt_box_autoadd_i_64(arr[4]),
      updatedCredential: dco_decode_opt_box_autoadd_secure_credential(arr[5]),
      updatedMimoCredential: dco_decode_opt_box_autoadd_mimo_credential(arr[6]),
    );
  }

  @protected
  UsageSnapshot dco_decode_usage_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return UsageSnapshot(
      account: dco_decode_account_info(arr[0]),
      windows: dco_decode_list_quota_window(arr[1]),
      balances: dco_decode_list_balance_metric(arr[2]),
      providerQuotas: dco_decode_list_provider_quota_metric(arr[3]),
      resetCreditsAvailable: dco_decode_opt_box_autoadd_i_64(arr[4]),
      resetCredits: dco_decode_opt_list_reset_credit(arr[5]),
      credits: dco_decode_opt_box_autoadd_credits_snapshot(arr[6]),
      fetchedAt: dco_decode_i_64(arr[7]),
    );
  }

  @protected
  UsageState dco_decode_usage_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UsageState.values[raw as int];
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AccountDetails sse_decode_account_details(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_email = sse_decode_opt_String(deserializer);
    var var_fetchedAt = sse_decode_i_64(deserializer);
    return AccountDetails(
      createdAt: var_createdAt,
      email: var_email,
      fetchedAt: var_fetchedAt,
    );
  }

  @protected
  AccountInfo sse_decode_account_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_provider = sse_decode_provider_kind(deserializer);
    var var_identityHash = sse_decode_String(deserializer);
    var var_email = sse_decode_opt_String(deserializer);
    var var_plan = sse_decode_opt_String(deserializer);
    var var_workspaceId = sse_decode_opt_String(deserializer);
    var var_isFedramp = sse_decode_bool(deserializer);
    var var_loginState = sse_decode_login_state(deserializer);
    var var_lastSuccessfulRefresh = sse_decode_opt_box_autoadd_i_64(
      deserializer,
    );
    var var_credentialStatus = sse_decode_credential_status(deserializer);
    return AccountInfo(
      provider: var_provider,
      identityHash: var_identityHash,
      email: var_email,
      plan: var_plan,
      workspaceId: var_workspaceId,
      isFedramp: var_isFedramp,
      loginState: var_loginState,
      lastSuccessfulRefresh: var_lastSuccessfulRefresh,
      credentialStatus: var_credentialStatus,
    );
  }

  @protected
  BalanceMetric sse_decode_balance_metric(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_amount = sse_decode_String(deserializer);
    var var_currency = sse_decode_opt_String(deserializer);
    var var_primary = sse_decode_bool(deserializer);
    return BalanceMetric(
      id: var_id,
      label: var_label,
      amount: var_amount,
      currency: var_currency,
      primary: var_primary,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AccountDetails sse_decode_box_autoadd_account_details(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_account_details(deserializer));
  }

  @protected
  AccountInfo sse_decode_box_autoadd_account_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_account_info(deserializer));
  }

  @protected
  CreditsSnapshot sse_decode_box_autoadd_credits_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_credits_snapshot(deserializer));
  }

  @protected
  DeviceCodeLoginComplete sse_decode_box_autoadd_device_code_login_complete(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_device_code_login_complete(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  MimoCredential sse_decode_box_autoadd_mimo_credential(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mimo_credential(deserializer));
  }

  @protected
  ProfileUsage sse_decode_box_autoadd_profile_usage(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_profile_usage(deserializer));
  }

  @protected
  SecureCredential sse_decode_box_autoadd_secure_credential(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_secure_credential(deserializer));
  }

  @protected
  UsageSnapshot sse_decode_box_autoadd_usage_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_usage_snapshot(deserializer));
  }

  @protected
  CredentialStatus sse_decode_credential_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CredentialStatus.values[inner];
  }

  @protected
  CreditsSnapshot sse_decode_credits_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hasCredits = sse_decode_bool(deserializer);
    var var_unlimited = sse_decode_bool(deserializer);
    var var_balance = sse_decode_opt_String(deserializer);
    return CreditsSnapshot(
      hasCredits: var_hasCredits,
      unlimited: var_unlimited,
      balance: var_balance,
    );
  }

  @protected
  DailyTokenBucket sse_decode_daily_token_bucket(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startDate = sse_decode_String(deserializer);
    var var_tokens = sse_decode_i_64(deserializer);
    return DailyTokenBucket(startDate: var_startDate, tokens: var_tokens);
  }

  @protected
  DeviceCodeLoginComplete sse_decode_device_code_login_complete(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_credential = sse_decode_secure_credential(deserializer);
    var var_account = sse_decode_account_info(deserializer);
    return DeviceCodeLoginComplete(
      credential: var_credential,
      account: var_account,
    );
  }

  @protected
  DeviceCodeLoginPoll sse_decode_device_code_login_poll(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pending = sse_decode_bool(deserializer);
    var var_completed = sse_decode_opt_box_autoadd_device_code_login_complete(
      deserializer,
    );
    return DeviceCodeLoginPoll(pending: var_pending, completed: var_completed);
  }

  @protected
  DeviceCodeLoginStart sse_decode_device_code_login_start(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_loginId = sse_decode_String(deserializer);
    var var_verificationUrl = sse_decode_String(deserializer);
    var var_userCode = sse_decode_String(deserializer);
    var var_pollIntervalSeconds = sse_decode_i_64(deserializer);
    return DeviceCodeLoginStart(
      loginId: var_loginId,
      verificationUrl: var_verificationUrl,
      userCode: var_userCode,
      pollIntervalSeconds: var_pollIntervalSeconds,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  HistoryPoint sse_decode_history_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timestamp = sse_decode_i_64(deserializer);
    var var_windowId = sse_decode_String(deserializer);
    var var_usedPercent = sse_decode_f_64(deserializer);
    return HistoryPoint(
      timestamp: var_timestamp,
      windowId: var_windowId,
      usedPercent: var_usedPercent,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<BalanceMetric> sse_decode_list_balance_metric(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BalanceMetric>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_balance_metric(deserializer));
    }
    return ans_;
  }

  @protected
  List<DailyTokenBucket> sse_decode_list_daily_token_bucket(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DailyTokenBucket>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_daily_token_bucket(deserializer));
    }
    return ans_;
  }

  @protected
  List<HistoryPoint> sse_decode_list_history_point(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HistoryPoint>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_history_point(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProviderQuotaMetric> sse_decode_list_provider_quota_metric(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProviderQuotaMetric>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_provider_quota_metric(deserializer));
    }
    return ans_;
  }

  @protected
  List<QuotaWindow> sse_decode_list_quota_window(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <QuotaWindow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_quota_window(deserializer));
    }
    return ans_;
  }

  @protected
  List<ResetCredit> sse_decode_list_reset_credit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ResetCredit>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_reset_credit(deserializer));
    }
    return ans_;
  }

  @protected
  List<SyncLogEntry> sse_decode_list_sync_log_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SyncLogEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sync_log_entry(deserializer));
    }
    return ans_;
  }

  @protected
  LoginState sse_decode_login_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return LoginState.values[inner];
  }

  @protected
  MimoCredential sse_decode_mimo_credential(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_String(deserializer);
    var var_passToken = sse_decode_String(deserializer);
    var var_serviceToken = sse_decode_String(deserializer);
    var var_serviceSlh = sse_decode_String(deserializer);
    var var_servicePh = sse_decode_String(deserializer);
    return MimoCredential(
      userId: var_userId,
      passToken: var_passToken,
      serviceToken: var_serviceToken,
      serviceSlh: var_serviceSlh,
      servicePh: var_servicePh,
    );
  }

  @protected
  MimoLoginResult sse_decode_mimo_login_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_account = sse_decode_opt_box_autoadd_account_info(deserializer);
    var var_credential = sse_decode_opt_box_autoadd_mimo_credential(
      deserializer,
    );
    var var_challengeUrl = sse_decode_opt_String(deserializer);
    return MimoLoginResult(
      account: var_account,
      credential: var_credential,
      challengeUrl: var_challengeUrl,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AccountDetails? sse_decode_opt_box_autoadd_account_details(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_account_details(deserializer));
    } else {
      return null;
    }
  }

  @protected
  AccountInfo? sse_decode_opt_box_autoadd_account_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_account_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  CreditsSnapshot? sse_decode_opt_box_autoadd_credits_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_credits_snapshot(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DeviceCodeLoginComplete?
  sse_decode_opt_box_autoadd_device_code_login_complete(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_device_code_login_complete(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MimoCredential? sse_decode_opt_box_autoadd_mimo_credential(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_mimo_credential(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProfileUsage? sse_decode_opt_box_autoadd_profile_usage(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_profile_usage(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SecureCredential? sse_decode_opt_box_autoadd_secure_credential(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_secure_credential(deserializer));
    } else {
      return null;
    }
  }

  @protected
  UsageSnapshot? sse_decode_opt_box_autoadd_usage_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_usage_snapshot(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<ResetCredit>? sse_decode_opt_list_reset_credit(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_reset_credit(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProfileUsage sse_decode_profile_usage(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_summary = sse_decode_token_usage_summary(deserializer);
    var var_dailyUsageBuckets = sse_decode_list_daily_token_bucket(
      deserializer,
    );
    var var_fetchedAt = sse_decode_i_64(deserializer);
    return ProfileUsage(
      summary: var_summary,
      dailyUsageBuckets: var_dailyUsageBuckets,
      fetchedAt: var_fetchedAt,
    );
  }

  @protected
  ProviderKind sse_decode_provider_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ProviderKind.values[inner];
  }

  @protected
  ProviderQuotaMetric sse_decode_provider_quota_metric(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_used = sse_decode_String(deserializer);
    var var_limit = sse_decode_String(deserializer);
    var var_remaining = sse_decode_String(deserializer);
    var var_usedPercent = sse_decode_f_64(deserializer);
    var var_expiresAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_unit = sse_decode_String(deserializer);
    return ProviderQuotaMetric(
      id: var_id,
      title: var_title,
      used: var_used,
      limit: var_limit,
      remaining: var_remaining,
      usedPercent: var_usedPercent,
      expiresAt: var_expiresAt,
      unit: var_unit,
    );
  }

  @protected
  QuotaWindow sse_decode_quota_window(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_usedPercent = sse_decode_f_64(deserializer);
    var var_resetAt = sse_decode_i_64(deserializer);
    var var_windowSeconds = sse_decode_i_64(deserializer);
    return QuotaWindow(
      id: var_id,
      title: var_title,
      usedPercent: var_usedPercent,
      resetAt: var_resetAt,
      windowSeconds: var_windowSeconds,
    );
  }

  @protected
  ResetCredit sse_decode_reset_credit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_grantedAt = sse_decode_i_64(deserializer);
    var var_expiresAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    return ResetCredit(
      id: var_id,
      status: var_status,
      grantedAt: var_grantedAt,
      expiresAt: var_expiresAt,
      title: var_title,
      description: var_description,
    );
  }

  @protected
  SecureCredential sse_decode_secure_credential(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_idToken = sse_decode_String(deserializer);
    var var_accessToken = sse_decode_String(deserializer);
    var var_refreshToken = sse_decode_String(deserializer);
    return SecureCredential(
      idToken: var_idToken,
      accessToken: var_accessToken,
      refreshToken: var_refreshToken,
    );
  }

  @protected
  SyncLogEntry sse_decode_sync_log_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_accountIdentityHash = sse_decode_String(deserializer);
    var var_trigger = sse_decode_sync_trigger(deserializer);
    var var_endpoint = sse_decode_String(deserializer);
    var var_startedAt = sse_decode_i_64(deserializer);
    var var_durationMs = sse_decode_i_64(deserializer);
    var var_statusCode = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_resultState = sse_decode_String(deserializer);
    var var_errorKind = sse_decode_opt_String(deserializer);
    var var_responseBody = sse_decode_String(deserializer);
    var var_truncated = sse_decode_bool(deserializer);
    return SyncLogEntry(
      id: var_id,
      accountIdentityHash: var_accountIdentityHash,
      trigger: var_trigger,
      endpoint: var_endpoint,
      startedAt: var_startedAt,
      durationMs: var_durationMs,
      statusCode: var_statusCode,
      resultState: var_resultState,
      errorKind: var_errorKind,
      responseBody: var_responseBody,
      truncated: var_truncated,
    );
  }

  @protected
  SyncTrigger sse_decode_sync_trigger(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SyncTrigger.values[inner];
  }

  @protected
  TokenUsageSummary sse_decode_token_usage_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lifetimeTokens = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_peakDailyTokens = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_longestRunningTurnSec = sse_decode_opt_box_autoadd_i_64(
      deserializer,
    );
    var var_currentStreakDays = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_longestStreakDays = sse_decode_opt_box_autoadd_i_64(deserializer);
    return TokenUsageSummary(
      lifetimeTokens: var_lifetimeTokens,
      peakDailyTokens: var_peakDailyTokens,
      longestRunningTurnSec: var_longestRunningTurnSec,
      currentStreakDays: var_currentStreakDays,
      longestStreakDays: var_longestStreakDays,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UsageResult sse_decode_usage_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_snapshot = sse_decode_opt_box_autoadd_usage_snapshot(deserializer);
    var var_state = sse_decode_usage_state(deserializer);
    var var_showingCachedData = sse_decode_bool(deserializer);
    var var_message = sse_decode_opt_String(deserializer);
    var var_retryAfterSeconds = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_updatedCredential = sse_decode_opt_box_autoadd_secure_credential(
      deserializer,
    );
    var var_updatedMimoCredential = sse_decode_opt_box_autoadd_mimo_credential(
      deserializer,
    );
    return UsageResult(
      snapshot: var_snapshot,
      state: var_state,
      showingCachedData: var_showingCachedData,
      message: var_message,
      retryAfterSeconds: var_retryAfterSeconds,
      updatedCredential: var_updatedCredential,
      updatedMimoCredential: var_updatedMimoCredential,
    );
  }

  @protected
  UsageSnapshot sse_decode_usage_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_account = sse_decode_account_info(deserializer);
    var var_windows = sse_decode_list_quota_window(deserializer);
    var var_balances = sse_decode_list_balance_metric(deserializer);
    var var_providerQuotas = sse_decode_list_provider_quota_metric(
      deserializer,
    );
    var var_resetCreditsAvailable = sse_decode_opt_box_autoadd_i_64(
      deserializer,
    );
    var var_resetCredits = sse_decode_opt_list_reset_credit(deserializer);
    var var_credits = sse_decode_opt_box_autoadd_credits_snapshot(deserializer);
    var var_fetchedAt = sse_decode_i_64(deserializer);
    return UsageSnapshot(
      account: var_account,
      windows: var_windows,
      balances: var_balances,
      providerQuotas: var_providerQuotas,
      resetCreditsAvailable: var_resetCreditsAvailable,
      resetCredits: var_resetCredits,
      credits: var_credits,
      fetchedAt: var_fetchedAt,
    );
  }

  @protected
  UsageState sse_decode_usage_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return UsageState.values[inner];
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_account_details(
    AccountDetails self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_opt_String(self.email, serializer);
    sse_encode_i_64(self.fetchedAt, serializer);
  }

  @protected
  void sse_encode_account_info(AccountInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_provider_kind(self.provider, serializer);
    sse_encode_String(self.identityHash, serializer);
    sse_encode_opt_String(self.email, serializer);
    sse_encode_opt_String(self.plan, serializer);
    sse_encode_opt_String(self.workspaceId, serializer);
    sse_encode_bool(self.isFedramp, serializer);
    sse_encode_login_state(self.loginState, serializer);
    sse_encode_opt_box_autoadd_i_64(self.lastSuccessfulRefresh, serializer);
    sse_encode_credential_status(self.credentialStatus, serializer);
  }

  @protected
  void sse_encode_balance_metric(BalanceMetric self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.amount, serializer);
    sse_encode_opt_String(self.currency, serializer);
    sse_encode_bool(self.primary, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_account_details(
    AccountDetails self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_account_details(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_account_info(
    AccountInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_account_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_credits_snapshot(
    CreditsSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_credits_snapshot(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_device_code_login_complete(
    DeviceCodeLoginComplete self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_device_code_login_complete(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_mimo_credential(
    MimoCredential self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mimo_credential(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_profile_usage(
    ProfileUsage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_profile_usage(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_secure_credential(
    SecureCredential self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_secure_credential(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_usage_snapshot(
    UsageSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usage_snapshot(self, serializer);
  }

  @protected
  void sse_encode_credential_status(
    CredentialStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_credits_snapshot(
    CreditsSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.hasCredits, serializer);
    sse_encode_bool(self.unlimited, serializer);
    sse_encode_opt_String(self.balance, serializer);
  }

  @protected
  void sse_encode_daily_token_bucket(
    DailyTokenBucket self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.startDate, serializer);
    sse_encode_i_64(self.tokens, serializer);
  }

  @protected
  void sse_encode_device_code_login_complete(
    DeviceCodeLoginComplete self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_secure_credential(self.credential, serializer);
    sse_encode_account_info(self.account, serializer);
  }

  @protected
  void sse_encode_device_code_login_poll(
    DeviceCodeLoginPoll self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.pending, serializer);
    sse_encode_opt_box_autoadd_device_code_login_complete(
      self.completed,
      serializer,
    );
  }

  @protected
  void sse_encode_device_code_login_start(
    DeviceCodeLoginStart self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.loginId, serializer);
    sse_encode_String(self.verificationUrl, serializer);
    sse_encode_String(self.userCode, serializer);
    sse_encode_i_64(self.pollIntervalSeconds, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_history_point(HistoryPoint self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.timestamp, serializer);
    sse_encode_String(self.windowId, serializer);
    sse_encode_f_64(self.usedPercent, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_balance_metric(
    List<BalanceMetric> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_balance_metric(item, serializer);
    }
  }

  @protected
  void sse_encode_list_daily_token_bucket(
    List<DailyTokenBucket> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_daily_token_bucket(item, serializer);
    }
  }

  @protected
  void sse_encode_list_history_point(
    List<HistoryPoint> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_history_point(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_provider_quota_metric(
    List<ProviderQuotaMetric> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_provider_quota_metric(item, serializer);
    }
  }

  @protected
  void sse_encode_list_quota_window(
    List<QuotaWindow> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_quota_window(item, serializer);
    }
  }

  @protected
  void sse_encode_list_reset_credit(
    List<ResetCredit> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_reset_credit(item, serializer);
    }
  }

  @protected
  void sse_encode_list_sync_log_entry(
    List<SyncLogEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sync_log_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_login_state(LoginState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_mimo_credential(
    MimoCredential self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.passToken, serializer);
    sse_encode_String(self.serviceToken, serializer);
    sse_encode_String(self.serviceSlh, serializer);
    sse_encode_String(self.servicePh, serializer);
  }

  @protected
  void sse_encode_mimo_login_result(
    MimoLoginResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_account_info(self.account, serializer);
    sse_encode_opt_box_autoadd_mimo_credential(self.credential, serializer);
    sse_encode_opt_String(self.challengeUrl, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_account_details(
    AccountDetails? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_account_details(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_account_info(
    AccountInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_account_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_credits_snapshot(
    CreditsSnapshot? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_credits_snapshot(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_device_code_login_complete(
    DeviceCodeLoginComplete? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_device_code_login_complete(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_mimo_credential(
    MimoCredential? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_mimo_credential(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_profile_usage(
    ProfileUsage? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_profile_usage(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_secure_credential(
    SecureCredential? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_secure_credential(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_usage_snapshot(
    UsageSnapshot? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_usage_snapshot(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_reset_credit(
    List<ResetCredit>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_reset_credit(self, serializer);
    }
  }

  @protected
  void sse_encode_profile_usage(ProfileUsage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_token_usage_summary(self.summary, serializer);
    sse_encode_list_daily_token_bucket(self.dailyUsageBuckets, serializer);
    sse_encode_i_64(self.fetchedAt, serializer);
  }

  @protected
  void sse_encode_provider_kind(ProviderKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_provider_quota_metric(
    ProviderQuotaMetric self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.used, serializer);
    sse_encode_String(self.limit, serializer);
    sse_encode_String(self.remaining, serializer);
    sse_encode_f_64(self.usedPercent, serializer);
    sse_encode_opt_box_autoadd_i_64(self.expiresAt, serializer);
    sse_encode_String(self.unit, serializer);
  }

  @protected
  void sse_encode_quota_window(QuotaWindow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_f_64(self.usedPercent, serializer);
    sse_encode_i_64(self.resetAt, serializer);
    sse_encode_i_64(self.windowSeconds, serializer);
  }

  @protected
  void sse_encode_reset_credit(ResetCredit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_i_64(self.grantedAt, serializer);
    sse_encode_opt_box_autoadd_i_64(self.expiresAt, serializer);
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.description, serializer);
  }

  @protected
  void sse_encode_secure_credential(
    SecureCredential self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.idToken, serializer);
    sse_encode_String(self.accessToken, serializer);
    sse_encode_String(self.refreshToken, serializer);
  }

  @protected
  void sse_encode_sync_log_entry(SyncLogEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.accountIdentityHash, serializer);
    sse_encode_sync_trigger(self.trigger, serializer);
    sse_encode_String(self.endpoint, serializer);
    sse_encode_i_64(self.startedAt, serializer);
    sse_encode_i_64(self.durationMs, serializer);
    sse_encode_opt_box_autoadd_i_64(self.statusCode, serializer);
    sse_encode_String(self.resultState, serializer);
    sse_encode_opt_String(self.errorKind, serializer);
    sse_encode_String(self.responseBody, serializer);
    sse_encode_bool(self.truncated, serializer);
  }

  @protected
  void sse_encode_sync_trigger(SyncTrigger self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_token_usage_summary(
    TokenUsageSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.lifetimeTokens, serializer);
    sse_encode_opt_box_autoadd_i_64(self.peakDailyTokens, serializer);
    sse_encode_opt_box_autoadd_i_64(self.longestRunningTurnSec, serializer);
    sse_encode_opt_box_autoadd_i_64(self.currentStreakDays, serializer);
    sse_encode_opt_box_autoadd_i_64(self.longestStreakDays, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usage_result(UsageResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_usage_snapshot(self.snapshot, serializer);
    sse_encode_usage_state(self.state, serializer);
    sse_encode_bool(self.showingCachedData, serializer);
    sse_encode_opt_String(self.message, serializer);
    sse_encode_opt_box_autoadd_i_64(self.retryAfterSeconds, serializer);
    sse_encode_opt_box_autoadd_secure_credential(
      self.updatedCredential,
      serializer,
    );
    sse_encode_opt_box_autoadd_mimo_credential(
      self.updatedMimoCredential,
      serializer,
    );
  }

  @protected
  void sse_encode_usage_snapshot(UsageSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_account_info(self.account, serializer);
    sse_encode_list_quota_window(self.windows, serializer);
    sse_encode_list_balance_metric(self.balances, serializer);
    sse_encode_list_provider_quota_metric(self.providerQuotas, serializer);
    sse_encode_opt_box_autoadd_i_64(self.resetCreditsAvailable, serializer);
    sse_encode_opt_list_reset_credit(self.resetCredits, serializer);
    sse_encode_opt_box_autoadd_credits_snapshot(self.credits, serializer);
    sse_encode_i_64(self.fetchedAt, serializer);
  }

  @protected
  void sse_encode_usage_state(UsageState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }
}
