// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/application.dart';
import 'api/system.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1386335933;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'ai_usage_core',
        ioDirectory: '../rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<DeviceCodeLoginStart> crateApiApplicationBeginDeviceLogin();

  Future<UsageResult> crateApiApplicationCachedUsage({
    required AccountInfo account,
  });

  Future<void> crateApiApplicationCancelDeviceLogin({required String loginId});

  Future<void> crateApiApplicationInitializeCore({
    required String databasePath,
  });

  Future<DeviceCodeLoginComplete> crateApiApplicationImportCodexAuthJson({
    required Uint8List content,
  });

  Future<String> crateApiSystemPing();

  Future<DeviceCodeLoginPoll> crateApiApplicationPollDeviceLogin({
    required String loginId,
  });

  Future<UsageResult> crateApiApplicationRefreshUsage({
    required SecureCredential credential,
  });

  Future<void> crateApiApplicationRemoveAccountData({
    required String accountIdentityHash,
  });

  Future<List<HistoryPoint>> crateApiApplicationUsageHistory({
    required String accountIdentityHash,
    required PlatformInt64 since,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<DeviceCodeLoginStart> crateApiApplicationBeginDeviceLogin() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_code_login_start,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationBeginDeviceLoginConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationBeginDeviceLoginConstMeta =>
      const TaskConstMeta(debugName: "begin_device_login", argNames: []);

  @override
  Future<UsageResult> crateApiApplicationCachedUsage({
    required AccountInfo account,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_account_info(account, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usage_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationCachedUsageConstMeta,
        argValues: [account],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationCachedUsageConstMeta =>
      const TaskConstMeta(debugName: "cached_usage", argNames: ["account"]);

  @override
  Future<void> crateApiApplicationCancelDeviceLogin({required String loginId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(loginId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationCancelDeviceLoginConstMeta,
        argValues: [loginId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationCancelDeviceLoginConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_device_login",
        argNames: ["loginId"],
      );

  @override
  Future<void> crateApiApplicationInitializeCore({
    required String databasePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(databasePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationInitializeCoreConstMeta,
        argValues: [databasePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationInitializeCoreConstMeta =>
      const TaskConstMeta(
        debugName: "initialize_core",
        argNames: ["databasePath"],
      );

  @override
  Future<DeviceCodeLoginComplete> crateApiApplicationImportCodexAuthJson({
    required Uint8List content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_strict(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_code_login_complete,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationImportCodexAuthJsonConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationImportCodexAuthJsonConstMeta =>
      const TaskConstMeta(
        debugName: "import_codex_auth_json",
        argNames: ["content"],
      );

  @override
  Future<String> crateApiSystemPing() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSystemPingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSystemPingConstMeta =>
      const TaskConstMeta(debugName: "ping", argNames: []);

  @override
  Future<DeviceCodeLoginPoll> crateApiApplicationPollDeviceLogin({
    required String loginId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(loginId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_code_login_poll,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationPollDeviceLoginConstMeta,
        argValues: [loginId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationPollDeviceLoginConstMeta =>
      const TaskConstMeta(
        debugName: "poll_device_login",
        argNames: ["loginId"],
      );

  @override
  Future<UsageResult> crateApiApplicationRefreshUsage({
    required SecureCredential credential,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_secure_credential(credential, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usage_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApplicationRefreshUsageConstMeta,
        argValues: [credential],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationRefreshUsageConstMeta =>
      const TaskConstMeta(debugName: "refresh_usage", argNames: ["credential"]);

  @override
  Future<void> crateApiApplicationRemoveAccountData({
    required String accountIdentityHash,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(accountIdentityHash, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationRemoveAccountDataConstMeta,
        argValues: [accountIdentityHash],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationRemoveAccountDataConstMeta =>
      const TaskConstMeta(
        debugName: "remove_account_data",
        argNames: ["accountIdentityHash"],
      );

  @override
  Future<List<HistoryPoint>> crateApiApplicationUsageHistory({
    required String accountIdentityHash,
    required PlatformInt64 since,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(accountIdentityHash, serializer);
          sse_encode_i_64(since, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_history_point,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplicationUsageHistoryConstMeta,
        argValues: [accountIdentityHash, since],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplicationUsageHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "usage_history",
        argNames: ["accountIdentityHash", "since"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AccountInfo dco_decode_account_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return AccountInfo(
      identityHash: dco_decode_String(arr[0]),
      email: dco_decode_opt_String(arr[1]),
      plan: dco_decode_opt_String(arr[2]),
      workspaceId: dco_decode_opt_String(arr[3]),
      isFedramp: dco_decode_bool(arr[4]),
      loginState: dco_decode_login_state(arr[5]),
      lastSuccessfulRefresh: dco_decode_opt_box_autoadd_i_64(arr[6]),
      credentialStatus: dco_decode_credential_status(arr[7]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AccountInfo dco_decode_box_autoadd_account_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_account_info(raw);
  }

  @protected
  DeviceCodeLoginComplete dco_decode_box_autoadd_device_code_login_complete(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_device_code_login_complete(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  SecureCredential dco_decode_box_autoadd_secure_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_secure_credential(raw);
  }

  @protected
  UsageSnapshot dco_decode_box_autoadd_usage_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_usage_snapshot(raw);
  }

  @protected
  CredentialStatus dco_decode_credential_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CredentialStatus.values[raw as int];
  }

  @protected
  DeviceCodeLoginComplete dco_decode_device_code_login_complete(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DeviceCodeLoginComplete(
      credential: dco_decode_secure_credential(arr[0]),
      account: dco_decode_account_info(arr[1]),
    );
  }

  @protected
  DeviceCodeLoginPoll dco_decode_device_code_login_poll(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DeviceCodeLoginPoll(
      pending: dco_decode_bool(arr[0]),
      completed: dco_decode_opt_box_autoadd_device_code_login_complete(arr[1]),
    );
  }

  @protected
  DeviceCodeLoginStart dco_decode_device_code_login_start(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DeviceCodeLoginStart(
      loginId: dco_decode_String(arr[0]),
      verificationUrl: dco_decode_String(arr[1]),
      userCode: dco_decode_String(arr[2]),
      pollIntervalSeconds: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  HistoryPoint dco_decode_history_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return HistoryPoint(
      timestamp: dco_decode_i_64(arr[0]),
      windowId: dco_decode_String(arr[1]),
      usedPercent: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<HistoryPoint> dco_decode_list_history_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_history_point).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<QuotaWindow> dco_decode_list_quota_window(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_quota_window).toList();
  }

  @protected
  List<ResetCredit> dco_decode_list_reset_credit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_reset_credit).toList();
  }

  @protected
  LoginState dco_decode_login_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LoginState.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DeviceCodeLoginComplete?
  dco_decode_opt_box_autoadd_device_code_login_complete(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_device_code_login_complete(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  SecureCredential? dco_decode_opt_box_autoadd_secure_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_secure_credential(raw);
  }

  @protected
  UsageSnapshot? dco_decode_opt_box_autoadd_usage_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_usage_snapshot(raw);
  }

  @protected
  List<ResetCredit>? dco_decode_opt_list_reset_credit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_reset_credit(raw);
  }

  @protected
  QuotaWindow dco_decode_quota_window(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return QuotaWindow(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      usedPercent: dco_decode_f_64(arr[2]),
      resetAt: dco_decode_i_64(arr[3]),
      windowSeconds: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  ResetCredit dco_decode_reset_credit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ResetCredit(
      id: dco_decode_String(arr[0]),
      status: dco_decode_String(arr[1]),
      grantedAt: dco_decode_i_64(arr[2]),
      expiresAt: dco_decode_opt_box_autoadd_i_64(arr[3]),
      title: dco_decode_opt_String(arr[4]),
      description: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  SecureCredential dco_decode_secure_credential(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SecureCredential(
      idToken: dco_decode_String(arr[0]),
      accessToken: dco_decode_String(arr[1]),
      refreshToken: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UsageResult dco_decode_usage_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return UsageResult(
      snapshot: dco_decode_opt_box_autoadd_usage_snapshot(arr[0]),
      state: dco_decode_usage_state(arr[1]),
      showingCachedData: dco_decode_bool(arr[2]),
      message: dco_decode_opt_String(arr[3]),
      retryAfterSeconds: dco_decode_opt_box_autoadd_i_64(arr[4]),
      updatedCredential: dco_decode_opt_box_autoadd_secure_credential(arr[5]),
    );
  }

  @protected
  UsageSnapshot dco_decode_usage_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return UsageSnapshot(
      account: dco_decode_account_info(arr[0]),
      windows: dco_decode_list_quota_window(arr[1]),
      resetCreditsAvailable: dco_decode_opt_box_autoadd_i_64(arr[2]),
      resetCredits: dco_decode_opt_list_reset_credit(arr[3]),
      fetchedAt: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  UsageState dco_decode_usage_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UsageState.values[raw as int];
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AccountInfo sse_decode_account_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_identityHash = sse_decode_String(deserializer);
    var var_email = sse_decode_opt_String(deserializer);
    var var_plan = sse_decode_opt_String(deserializer);
    var var_workspaceId = sse_decode_opt_String(deserializer);
    var var_isFedramp = sse_decode_bool(deserializer);
    var var_loginState = sse_decode_login_state(deserializer);
    var var_lastSuccessfulRefresh = sse_decode_opt_box_autoadd_i_64(
      deserializer,
    );
    var var_credentialStatus = sse_decode_credential_status(deserializer);
    return AccountInfo(
      identityHash: var_identityHash,
      email: var_email,
      plan: var_plan,
      workspaceId: var_workspaceId,
      isFedramp: var_isFedramp,
      loginState: var_loginState,
      lastSuccessfulRefresh: var_lastSuccessfulRefresh,
      credentialStatus: var_credentialStatus,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AccountInfo sse_decode_box_autoadd_account_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_account_info(deserializer));
  }

  @protected
  DeviceCodeLoginComplete sse_decode_box_autoadd_device_code_login_complete(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_device_code_login_complete(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  SecureCredential sse_decode_box_autoadd_secure_credential(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_secure_credential(deserializer));
  }

  @protected
  UsageSnapshot sse_decode_box_autoadd_usage_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_usage_snapshot(deserializer));
  }

  @protected
  CredentialStatus sse_decode_credential_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CredentialStatus.values[inner];
  }

  @protected
  DeviceCodeLoginComplete sse_decode_device_code_login_complete(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_credential = sse_decode_secure_credential(deserializer);
    var var_account = sse_decode_account_info(deserializer);
    return DeviceCodeLoginComplete(
      credential: var_credential,
      account: var_account,
    );
  }

  @protected
  DeviceCodeLoginPoll sse_decode_device_code_login_poll(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pending = sse_decode_bool(deserializer);
    var var_completed = sse_decode_opt_box_autoadd_device_code_login_complete(
      deserializer,
    );
    return DeviceCodeLoginPoll(pending: var_pending, completed: var_completed);
  }

  @protected
  DeviceCodeLoginStart sse_decode_device_code_login_start(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_loginId = sse_decode_String(deserializer);
    var var_verificationUrl = sse_decode_String(deserializer);
    var var_userCode = sse_decode_String(deserializer);
    var var_pollIntervalSeconds = sse_decode_i_64(deserializer);
    return DeviceCodeLoginStart(
      loginId: var_loginId,
      verificationUrl: var_verificationUrl,
      userCode: var_userCode,
      pollIntervalSeconds: var_pollIntervalSeconds,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  HistoryPoint sse_decode_history_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timestamp = sse_decode_i_64(deserializer);
    var var_windowId = sse_decode_String(deserializer);
    var var_usedPercent = sse_decode_f_64(deserializer);
    return HistoryPoint(
      timestamp: var_timestamp,
      windowId: var_windowId,
      usedPercent: var_usedPercent,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<HistoryPoint> sse_decode_list_history_point(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HistoryPoint>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_history_point(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<QuotaWindow> sse_decode_list_quota_window(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <QuotaWindow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_quota_window(deserializer));
    }
    return ans_;
  }

  @protected
  List<ResetCredit> sse_decode_list_reset_credit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ResetCredit>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_reset_credit(deserializer));
    }
    return ans_;
  }

  @protected
  LoginState sse_decode_login_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return LoginState.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DeviceCodeLoginComplete?
  sse_decode_opt_box_autoadd_device_code_login_complete(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_device_code_login_complete(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SecureCredential? sse_decode_opt_box_autoadd_secure_credential(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_secure_credential(deserializer));
    } else {
      return null;
    }
  }

  @protected
  UsageSnapshot? sse_decode_opt_box_autoadd_usage_snapshot(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_usage_snapshot(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<ResetCredit>? sse_decode_opt_list_reset_credit(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_reset_credit(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QuotaWindow sse_decode_quota_window(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_usedPercent = sse_decode_f_64(deserializer);
    var var_resetAt = sse_decode_i_64(deserializer);
    var var_windowSeconds = sse_decode_i_64(deserializer);
    return QuotaWindow(
      id: var_id,
      title: var_title,
      usedPercent: var_usedPercent,
      resetAt: var_resetAt,
      windowSeconds: var_windowSeconds,
    );
  }

  @protected
  ResetCredit sse_decode_reset_credit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_grantedAt = sse_decode_i_64(deserializer);
    var var_expiresAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    return ResetCredit(
      id: var_id,
      status: var_status,
      grantedAt: var_grantedAt,
      expiresAt: var_expiresAt,
      title: var_title,
      description: var_description,
    );
  }

  @protected
  SecureCredential sse_decode_secure_credential(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_idToken = sse_decode_String(deserializer);
    var var_accessToken = sse_decode_String(deserializer);
    var var_refreshToken = sse_decode_String(deserializer);
    return SecureCredential(
      idToken: var_idToken,
      accessToken: var_accessToken,
      refreshToken: var_refreshToken,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UsageResult sse_decode_usage_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_snapshot = sse_decode_opt_box_autoadd_usage_snapshot(deserializer);
    var var_state = sse_decode_usage_state(deserializer);
    var var_showingCachedData = sse_decode_bool(deserializer);
    var var_message = sse_decode_opt_String(deserializer);
    var var_retryAfterSeconds = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_updatedCredential = sse_decode_opt_box_autoadd_secure_credential(
      deserializer,
    );
    return UsageResult(
      snapshot: var_snapshot,
      state: var_state,
      showingCachedData: var_showingCachedData,
      message: var_message,
      retryAfterSeconds: var_retryAfterSeconds,
      updatedCredential: var_updatedCredential,
    );
  }

  @protected
  UsageSnapshot sse_decode_usage_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_account = sse_decode_account_info(deserializer);
    var var_windows = sse_decode_list_quota_window(deserializer);
    var var_resetCreditsAvailable = sse_decode_opt_box_autoadd_i_64(
      deserializer,
    );
    var var_resetCredits = sse_decode_opt_list_reset_credit(deserializer);
    var var_fetchedAt = sse_decode_i_64(deserializer);
    return UsageSnapshot(
      account: var_account,
      windows: var_windows,
      resetCreditsAvailable: var_resetCreditsAvailable,
      resetCredits: var_resetCredits,
      fetchedAt: var_fetchedAt,
    );
  }

  @protected
  UsageState sse_decode_usage_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return UsageState.values[inner];
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_account_info(AccountInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.identityHash, serializer);
    sse_encode_opt_String(self.email, serializer);
    sse_encode_opt_String(self.plan, serializer);
    sse_encode_opt_String(self.workspaceId, serializer);
    sse_encode_bool(self.isFedramp, serializer);
    sse_encode_login_state(self.loginState, serializer);
    sse_encode_opt_box_autoadd_i_64(self.lastSuccessfulRefresh, serializer);
    sse_encode_credential_status(self.credentialStatus, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_account_info(
    AccountInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_account_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_device_code_login_complete(
    DeviceCodeLoginComplete self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_device_code_login_complete(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_secure_credential(
    SecureCredential self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_secure_credential(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_usage_snapshot(
    UsageSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usage_snapshot(self, serializer);
  }

  @protected
  void sse_encode_credential_status(
    CredentialStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_device_code_login_complete(
    DeviceCodeLoginComplete self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_secure_credential(self.credential, serializer);
    sse_encode_account_info(self.account, serializer);
  }

  @protected
  void sse_encode_device_code_login_poll(
    DeviceCodeLoginPoll self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.pending, serializer);
    sse_encode_opt_box_autoadd_device_code_login_complete(
      self.completed,
      serializer,
    );
  }

  @protected
  void sse_encode_device_code_login_start(
    DeviceCodeLoginStart self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.loginId, serializer);
    sse_encode_String(self.verificationUrl, serializer);
    sse_encode_String(self.userCode, serializer);
    sse_encode_i_64(self.pollIntervalSeconds, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_history_point(HistoryPoint self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.timestamp, serializer);
    sse_encode_String(self.windowId, serializer);
    sse_encode_f_64(self.usedPercent, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_history_point(
    List<HistoryPoint> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_history_point(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_quota_window(
    List<QuotaWindow> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_quota_window(item, serializer);
    }
  }

  @protected
  void sse_encode_list_reset_credit(
    List<ResetCredit> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_reset_credit(item, serializer);
    }
  }

  @protected
  void sse_encode_login_state(LoginState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_device_code_login_complete(
    DeviceCodeLoginComplete? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_device_code_login_complete(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_secure_credential(
    SecureCredential? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_secure_credential(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_usage_snapshot(
    UsageSnapshot? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_usage_snapshot(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_reset_credit(
    List<ResetCredit>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_reset_credit(self, serializer);
    }
  }

  @protected
  void sse_encode_quota_window(QuotaWindow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_f_64(self.usedPercent, serializer);
    sse_encode_i_64(self.resetAt, serializer);
    sse_encode_i_64(self.windowSeconds, serializer);
  }

  @protected
  void sse_encode_reset_credit(ResetCredit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_i_64(self.grantedAt, serializer);
    sse_encode_opt_box_autoadd_i_64(self.expiresAt, serializer);
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.description, serializer);
  }

  @protected
  void sse_encode_secure_credential(
    SecureCredential self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.idToken, serializer);
    sse_encode_String(self.accessToken, serializer);
    sse_encode_String(self.refreshToken, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usage_result(UsageResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_usage_snapshot(self.snapshot, serializer);
    sse_encode_usage_state(self.state, serializer);
    sse_encode_bool(self.showingCachedData, serializer);
    sse_encode_opt_String(self.message, serializer);
    sse_encode_opt_box_autoadd_i_64(self.retryAfterSeconds, serializer);
    sse_encode_opt_box_autoadd_secure_credential(
      self.updatedCredential,
      serializer,
    );
  }

  @protected
  void sse_encode_usage_snapshot(UsageSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_account_info(self.account, serializer);
    sse_encode_list_quota_window(self.windows, serializer);
    sse_encode_opt_box_autoadd_i_64(self.resetCreditsAvailable, serializer);
    sse_encode_opt_list_reset_credit(self.resetCredits, serializer);
    sse_encode_i_64(self.fetchedAt, serializer);
  }

  @protected
  void sse_encode_usage_state(UsageState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }
}
