// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AccountDetails {
  final PlatformInt64 createdAt;
  final String? email;
  final PlatformInt64 fetchedAt;

  const AccountDetails({
    required this.createdAt,
    this.email,
    required this.fetchedAt,
  });

  @override
  int get hashCode => createdAt.hashCode ^ email.hashCode ^ fetchedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountDetails &&
          runtimeType == other.runtimeType &&
          createdAt == other.createdAt &&
          email == other.email &&
          fetchedAt == other.fetchedAt;
}

/// Non-secret account metadata. `identity_hash` is the only account identifier
/// written to SQLite; it is a SHA-256 digest derived from JWT claims.
class AccountInfo {
  final ProviderKind provider;
  final String identityHash;
  final String? email;
  final String? plan;
  final String? workspaceId;
  final bool isFedramp;
  final LoginState loginState;
  final PlatformInt64? lastSuccessfulRefresh;
  final CredentialStatus credentialStatus;

  const AccountInfo({
    required this.provider,
    required this.identityHash,
    this.email,
    this.plan,
    this.workspaceId,
    required this.isFedramp,
    required this.loginState,
    this.lastSuccessfulRefresh,
    required this.credentialStatus,
  });

  @override
  int get hashCode =>
      provider.hashCode ^
      identityHash.hashCode ^
      email.hashCode ^
      plan.hashCode ^
      workspaceId.hashCode ^
      isFedramp.hashCode ^
      loginState.hashCode ^
      lastSuccessfulRefresh.hashCode ^
      credentialStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountInfo &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          identityHash == other.identityHash &&
          email == other.email &&
          plan == other.plan &&
          workspaceId == other.workspaceId &&
          isFedramp == other.isFedramp &&
          loginState == other.loginState &&
          lastSuccessfulRefresh == other.lastSuccessfulRefresh &&
          credentialStatus == other.credentialStatus;
}

class BalanceMetric {
  final String id;
  final String label;
  final String amount;
  final String? currency;
  final bool primary;

  const BalanceMetric({
    required this.id,
    required this.label,
    required this.amount,
    this.currency,
    required this.primary,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      amount.hashCode ^
      currency.hashCode ^
      primary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BalanceMetric &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          amount == other.amount &&
          currency == other.currency &&
          primary == other.primary;
}

enum CredentialStatus { available, missing, refreshRequired }

class CreditsSnapshot {
  final bool hasCredits;
  final bool unlimited;
  final String? balance;

  const CreditsSnapshot({
    required this.hasCredits,
    required this.unlimited,
    this.balance,
  });

  @override
  int get hashCode =>
      hasCredits.hashCode ^ unlimited.hashCode ^ balance.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreditsSnapshot &&
          runtimeType == other.runtimeType &&
          hasCredits == other.hasCredits &&
          unlimited == other.unlimited &&
          balance == other.balance;
}

class DailyTokenBucket {
  final String startDate;
  final PlatformInt64 tokens;

  const DailyTokenBucket({required this.startDate, required this.tokens});

  @override
  int get hashCode => startDate.hashCode ^ tokens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DailyTokenBucket &&
          runtimeType == other.runtimeType &&
          startDate == other.startDate &&
          tokens == other.tokens;
}

class DeviceCodeLoginComplete {
  final SecureCredential credential;
  final AccountInfo account;

  const DeviceCodeLoginComplete({
    required this.credential,
    required this.account,
  });

  @override
  int get hashCode => credential.hashCode ^ account.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceCodeLoginComplete &&
          runtimeType == other.runtimeType &&
          credential == other.credential &&
          account == other.account;
}

class DeviceCodeLoginPoll {
  final bool pending;
  final DeviceCodeLoginComplete? completed;

  const DeviceCodeLoginPoll({required this.pending, this.completed});

  @override
  int get hashCode => pending.hashCode ^ completed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceCodeLoginPoll &&
          runtimeType == other.runtimeType &&
          pending == other.pending &&
          completed == other.completed;
}

class DeviceCodeLoginStart {
  final String loginId;
  final String verificationUrl;
  final String userCode;
  final PlatformInt64 pollIntervalSeconds;

  const DeviceCodeLoginStart({
    required this.loginId,
    required this.verificationUrl,
    required this.userCode,
    required this.pollIntervalSeconds,
  });

  @override
  int get hashCode =>
      loginId.hashCode ^
      verificationUrl.hashCode ^
      userCode.hashCode ^
      pollIntervalSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceCodeLoginStart &&
          runtimeType == other.runtimeType &&
          loginId == other.loginId &&
          verificationUrl == other.verificationUrl &&
          userCode == other.userCode &&
          pollIntervalSeconds == other.pollIntervalSeconds;
}

class HistoryPoint {
  final PlatformInt64 timestamp;
  final String windowId;
  final double usedPercent;

  const HistoryPoint({
    required this.timestamp,
    required this.windowId,
    required this.usedPercent,
  });

  @override
  int get hashCode =>
      timestamp.hashCode ^ windowId.hashCode ^ usedPercent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryPoint &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          windowId == other.windowId &&
          usedPercent == other.usedPercent;
}

enum LoginState { signedIn, signedOut, expired }

class MimoCredential {
  final String userId;
  final String passToken;
  final String serviceToken;
  final String serviceSlh;
  final String servicePh;

  const MimoCredential({
    required this.userId,
    required this.passToken,
    required this.serviceToken,
    required this.serviceSlh,
    required this.servicePh,
  });

  @override
  int get hashCode =>
      userId.hashCode ^
      passToken.hashCode ^
      serviceToken.hashCode ^
      serviceSlh.hashCode ^
      servicePh.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MimoCredential &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          passToken == other.passToken &&
          serviceToken == other.serviceToken &&
          serviceSlh == other.serviceSlh &&
          servicePh == other.servicePh;
}

class MimoLoginResult {
  final AccountInfo? account;
  final MimoCredential? credential;
  final String? challengeUrl;

  const MimoLoginResult({this.account, this.credential, this.challengeUrl});

  @override
  int get hashCode =>
      account.hashCode ^ credential.hashCode ^ challengeUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MimoLoginResult &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          credential == other.credential &&
          challengeUrl == other.challengeUrl;
}

class ProfileUsage {
  final TokenUsageSummary summary;
  final List<DailyTokenBucket> dailyUsageBuckets;
  final PlatformInt64 fetchedAt;

  const ProfileUsage({
    required this.summary,
    required this.dailyUsageBuckets,
    required this.fetchedAt,
  });

  @override
  int get hashCode =>
      summary.hashCode ^ dailyUsageBuckets.hashCode ^ fetchedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileUsage &&
          runtimeType == other.runtimeType &&
          summary == other.summary &&
          dailyUsageBuckets == other.dailyUsageBuckets &&
          fetchedAt == other.fetchedAt;
}

enum ProviderKind { codex, deepSeek, mimo }

class ProviderQuotaMetric {
  final String id;
  final String title;
  final String used;
  final String limit;
  final String remaining;
  final double usedPercent;
  final PlatformInt64? expiresAt;
  final String unit;

  const ProviderQuotaMetric({
    required this.id,
    required this.title,
    required this.used,
    required this.limit,
    required this.remaining,
    required this.usedPercent,
    this.expiresAt,
    required this.unit,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      used.hashCode ^
      limit.hashCode ^
      remaining.hashCode ^
      usedPercent.hashCode ^
      expiresAt.hashCode ^
      unit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderQuotaMetric &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          used == other.used &&
          limit == other.limit &&
          remaining == other.remaining &&
          usedPercent == other.usedPercent &&
          expiresAt == other.expiresAt &&
          unit == other.unit;
}

class QuotaWindow {
  final String id;
  final String title;
  final double usedPercent;
  final PlatformInt64 resetAt;
  final PlatformInt64 windowSeconds;

  const QuotaWindow({
    required this.id,
    required this.title,
    required this.usedPercent,
    required this.resetAt,
    required this.windowSeconds,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      usedPercent.hashCode ^
      resetAt.hashCode ^
      windowSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuotaWindow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          usedPercent == other.usedPercent &&
          resetAt == other.resetAt &&
          windowSeconds == other.windowSeconds;
}

class ResetCredit {
  final String id;
  final String status;
  final PlatformInt64 grantedAt;
  final PlatformInt64? expiresAt;
  final String? title;
  final String? description;

  const ResetCredit({
    required this.id,
    required this.status,
    required this.grantedAt,
    this.expiresAt,
    this.title,
    this.description,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      status.hashCode ^
      grantedAt.hashCode ^
      expiresAt.hashCode ^
      title.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResetCredit &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          status == other.status &&
          grantedAt == other.grantedAt &&
          expiresAt == other.expiresAt &&
          title == other.title &&
          description == other.description;
}

class SecureCredential {
  final String idToken;
  final String accessToken;
  final String refreshToken;

  const SecureCredential({
    required this.idToken,
    required this.accessToken,
    required this.refreshToken,
  });

  @override
  int get hashCode =>
      idToken.hashCode ^ accessToken.hashCode ^ refreshToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SecureCredential &&
          runtimeType == other.runtimeType &&
          idToken == other.idToken &&
          accessToken == other.accessToken &&
          refreshToken == other.refreshToken;
}

class SyncLogEntry {
  final PlatformInt64 id;
  final String accountIdentityHash;
  final SyncTrigger trigger;
  final String endpoint;
  final PlatformInt64 startedAt;
  final PlatformInt64 durationMs;
  final PlatformInt64? statusCode;
  final String resultState;
  final String? errorKind;
  final String responseBody;
  final bool truncated;

  const SyncLogEntry({
    required this.id,
    required this.accountIdentityHash,
    required this.trigger,
    required this.endpoint,
    required this.startedAt,
    required this.durationMs,
    this.statusCode,
    required this.resultState,
    this.errorKind,
    required this.responseBody,
    required this.truncated,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      accountIdentityHash.hashCode ^
      trigger.hashCode ^
      endpoint.hashCode ^
      startedAt.hashCode ^
      durationMs.hashCode ^
      statusCode.hashCode ^
      resultState.hashCode ^
      errorKind.hashCode ^
      responseBody.hashCode ^
      truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncLogEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          accountIdentityHash == other.accountIdentityHash &&
          trigger == other.trigger &&
          endpoint == other.endpoint &&
          startedAt == other.startedAt &&
          durationMs == other.durationMs &&
          statusCode == other.statusCode &&
          resultState == other.resultState &&
          errorKind == other.errorKind &&
          responseBody == other.responseBody &&
          truncated == other.truncated;
}

enum SyncTrigger { manual, resume, foregroundTimer, background, pageLoad }

class TokenUsageSummary {
  final PlatformInt64? lifetimeTokens;
  final PlatformInt64? peakDailyTokens;
  final PlatformInt64? longestRunningTurnSec;
  final PlatformInt64? currentStreakDays;
  final PlatformInt64? longestStreakDays;

  const TokenUsageSummary({
    this.lifetimeTokens,
    this.peakDailyTokens,
    this.longestRunningTurnSec,
    this.currentStreakDays,
    this.longestStreakDays,
  });

  @override
  int get hashCode =>
      lifetimeTokens.hashCode ^
      peakDailyTokens.hashCode ^
      longestRunningTurnSec.hashCode ^
      currentStreakDays.hashCode ^
      longestStreakDays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TokenUsageSummary &&
          runtimeType == other.runtimeType &&
          lifetimeTokens == other.lifetimeTokens &&
          peakDailyTokens == other.peakDailyTokens &&
          longestRunningTurnSec == other.longestRunningTurnSec &&
          currentStreakDays == other.currentStreakDays &&
          longestStreakDays == other.longestStreakDays;
}

class UsageResult {
  final UsageSnapshot? snapshot;
  final UsageState state;
  final bool showingCachedData;
  final String? message;
  final PlatformInt64? retryAfterSeconds;

  /// Present only after an OAuth refresh or device-code sign-in. Flutter must
  /// replace its secure-storage value atomically and must never place this in
  /// SQLite or logs.
  final SecureCredential? updatedCredential;
  final MimoCredential? updatedMimoCredential;

  const UsageResult({
    this.snapshot,
    required this.state,
    required this.showingCachedData,
    this.message,
    this.retryAfterSeconds,
    this.updatedCredential,
    this.updatedMimoCredential,
  });

  @override
  int get hashCode =>
      snapshot.hashCode ^
      state.hashCode ^
      showingCachedData.hashCode ^
      message.hashCode ^
      retryAfterSeconds.hashCode ^
      updatedCredential.hashCode ^
      updatedMimoCredential.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UsageResult &&
          runtimeType == other.runtimeType &&
          snapshot == other.snapshot &&
          state == other.state &&
          showingCachedData == other.showingCachedData &&
          message == other.message &&
          retryAfterSeconds == other.retryAfterSeconds &&
          updatedCredential == other.updatedCredential &&
          updatedMimoCredential == other.updatedMimoCredential;
}

class UsageSnapshot {
  final AccountInfo account;
  final List<QuotaWindow> windows;
  final List<BalanceMetric> balances;
  final List<ProviderQuotaMetric> providerQuotas;
  final PlatformInt64? resetCreditsAvailable;
  final List<ResetCredit>? resetCredits;
  final CreditsSnapshot? credits;
  final PlatformInt64 fetchedAt;

  const UsageSnapshot({
    required this.account,
    required this.windows,
    required this.balances,
    required this.providerQuotas,
    this.resetCreditsAvailable,
    this.resetCredits,
    this.credits,
    required this.fetchedAt,
  });

  @override
  int get hashCode =>
      account.hashCode ^
      windows.hashCode ^
      balances.hashCode ^
      providerQuotas.hashCode ^
      resetCreditsAvailable.hashCode ^
      resetCredits.hashCode ^
      credits.hashCode ^
      fetchedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UsageSnapshot &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          windows == other.windows &&
          balances == other.balances &&
          providerQuotas == other.providerQuotas &&
          resetCreditsAvailable == other.resetCreditsAvailable &&
          resetCredits == other.resetCredits &&
          credits == other.credits &&
          fetchedAt == other.fetchedAt;
}

enum UsageState {
  fresh,
  stale,
  authExpired,
  offline,
  rateLimited,
  serverError,
  parseError,
}
