// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initializeCore({required String databasePath}) => RustLib
    .instance
    .api
    .crateApiApplicationInitializeCore(databasePath: databasePath);

Future<DeviceCodeLoginStart> beginDeviceLogin() =>
    RustLib.instance.api.crateApiApplicationBeginDeviceLogin();

Future<DeviceCodeLoginPoll> pollDeviceLogin({required String loginId}) =>
    RustLib.instance.api.crateApiApplicationPollDeviceLogin(loginId: loginId);

Future<void> cancelDeviceLogin({required String loginId}) =>
    RustLib.instance.api.crateApiApplicationCancelDeviceLogin(loginId: loginId);

Future<DeviceCodeLoginComplete> importCodexAuthJson({
  required List<int> content,
}) => RustLib.instance.api.crateApiApplicationImportCodexAuthJson(
  content: content,
);

Future<UsageResult> refreshUsage({
  required SecureCredential credential,
  required SyncTrigger trigger,
}) => RustLib.instance.api.crateApiApplicationRefreshUsage(
  credential: credential,
  trigger: trigger,
);

Future<UsageResult> refreshDeepseekUsage({
  required String apiKey,
  required SyncTrigger trigger,
}) => RustLib.instance.api.crateApiApplicationRefreshDeepseekUsage(
  apiKey: apiKey,
  trigger: trigger,
);

Future<MimoLoginResult> beginMimoLogin({
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiApplicationBeginMimoLogin(
  username: username,
  password: password,
);

Future<MimoLoginResult> completeMimoWebLogin({
  required String accountCookie,
  required String platformCookie,
}) => RustLib.instance.api.crateApiApplicationCompleteMimoWebLogin(
  accountCookie: accountCookie,
  platformCookie: platformCookie,
);

Future<UsageResult> refreshMimoUsage({
  required MimoCredential credential,
  required SyncTrigger trigger,
}) => RustLib.instance.api.crateApiApplicationRefreshMimoUsage(
  credential: credential,
  trigger: trigger,
);

Future<ProfileUsage> fetchProfileUsage({
  required SecureCredential credential,
  required SyncTrigger trigger,
}) => RustLib.instance.api.crateApiApplicationFetchProfileUsage(
  credential: credential,
  trigger: trigger,
);

Future<ProfileUsage?> cachedProfileUsage({
  required String accountIdentityHash,
}) => RustLib.instance.api.crateApiApplicationCachedProfileUsage(
  accountIdentityHash: accountIdentityHash,
);

Future<AccountDetails> fetchAccountDetails({
  required SecureCredential credential,
  required SyncTrigger trigger,
}) => RustLib.instance.api.crateApiApplicationFetchAccountDetails(
  credential: credential,
  trigger: trigger,
);

Future<AccountDetails?> cachedAccountDetails({
  required String accountIdentityHash,
}) => RustLib.instance.api.crateApiApplicationCachedAccountDetails(
  accountIdentityHash: accountIdentityHash,
);

Future<List<SyncLogEntry>> syncLogs() =>
    RustLib.instance.api.crateApiApplicationSyncLogs();

Future<UsageResult> cachedUsage({required AccountInfo account}) =>
    RustLib.instance.api.crateApiApplicationCachedUsage(account: account);

Future<List<HistoryPoint>> usageHistory({
  required String accountIdentityHash,
  required PlatformInt64 since,
}) => RustLib.instance.api.crateApiApplicationUsageHistory(
  accountIdentityHash: accountIdentityHash,
  since: since,
);

Future<void> removeAccountData({required String accountIdentityHash}) =>
    RustLib.instance.api.crateApiApplicationRemoveAccountData(
      accountIdentityHash: accountIdentityHash,
    );
