// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'dart:typed_data';

import '../frb_generated.dart';
import '../models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initializeCore({required String databasePath}) => RustLib
    .instance
    .api
    .crateApiApplicationInitializeCore(databasePath: databasePath);

Future<DeviceCodeLoginStart> beginDeviceLogin() =>
    RustLib.instance.api.crateApiApplicationBeginDeviceLogin();

Future<DeviceCodeLoginPoll> pollDeviceLogin({required String loginId}) =>
    RustLib.instance.api.crateApiApplicationPollDeviceLogin(loginId: loginId);

Future<void> cancelDeviceLogin({required String loginId}) =>
    RustLib.instance.api.crateApiApplicationCancelDeviceLogin(loginId: loginId);

Future<DeviceCodeLoginComplete> importCodexAuthJson({
  required Uint8List content,
}) => RustLib.instance.api.crateApiApplicationImportCodexAuthJson(
  content: content,
);

Future<UsageResult> refreshUsage({required SecureCredential credential}) =>
    RustLib.instance.api.crateApiApplicationRefreshUsage(
      credential: credential,
    );

Future<UsageResult> cachedUsage({required AccountInfo account}) =>
    RustLib.instance.api.crateApiApplicationCachedUsage(account: account);

Future<List<HistoryPoint>> usageHistory({
  required String accountIdentityHash,
  required PlatformInt64 since,
}) => RustLib.instance.api.crateApiApplicationUsageHistory(
  accountIdentityHash: accountIdentityHash,
  since: since,
);

Future<void> removeAccountData({required String accountIdentityHash}) =>
    RustLib.instance.api.crateApiApplicationRemoveAccountData(
      accountIdentityHash: accountIdentityHash,
    );
