// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Small Phase 1 health check. It deliberately has no network or storage side
/// effects and verifies the generated Rust-to-Dart binding on every platform.
Future<String> ping() => RustLib.instance.api.crateApiSystemPing();
